_target_: src.agent.core.Agent
memory:
  _target_: src.agent.memory.EpisodicMemory
  map_size: ${env.size}
  unknown_value: -1
perception:
  _target_: src.agent.perception.raycasting.RaycastPerception
  num_rays: 72
  vision_radius: 8.0
strategy:
  _target_: src.agent.strategy.greedy.GreedyStrategy
  vision_radius: 8
uncertainty_module:
  _target_: src.agent.uncertainty_quantification.mcdropout.MCDropoutUncertainty
  num_samples: 10
movement:
  _target_: src.agent.movement.engine.MovementEngine
  rules:
    - _target_: src.agent.movement.rules.ObstacleRule
    - _target_: src.agent.movement.rules.FrontierRule
    - _target_: src.agent.movement.rules.NoStayRule
    - _target_: src.agent.movement.rules.BudgetRule
      max_distance: 8