_target_: src.agent.core.Agent
max_steps: 40

memory:
  _target_: src.agent.memory.EpisodicMemory
  map_size: ${environment.size}
  unknown_value: -1
perception:
  _target_: src.agent.perception.raycasting.RaycastPerception
  num_rays: 72
  vision_radius: 8.0
strategy: ${strategy}
uncertainty_module:
  _target_: src.agent.uncertainty_quantification.mcdropout.MCDropoutUncertainty
  num_samples: 10
movement:
  _target_: src.agent.movement.engine.MovementEngine
  rules:
    - _target_: src.agent.movement.rules.ObstacleRule
    - _target_: src.agent.movement.rules.FrontierRule
    - _target_: src.agent.movement.rules.NoStayRule
    